runtime: go
api_version: go1

handlers:
  # API calls are handled by Go App
- url: /api/.*
  script: _go_app

  # let angular access assets
- url: /assets
  static_dir: static/assets

# If the path is empty, show static index.html file
- url: (.*)/
  static_files: static/index.html
  upload: static/index.html

- url: (.*)
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_files: static/index.html
  upload: static/index.html

# Serve favicon.ico on expected path
- url: /favicon\.ico
  static_files: static/assets/favicon.ico
  upload: static/assets/favicon\.ico



