runtime: go
api_version: go1

handlers:
  # API calls are handled by Go App
- url: /api/.*
  script: _go_app

- url: /index\.html
  static_files: static/index.html
  upload: static/index\.html

# Serve favicon.ico on expected path
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /ngsw-worker\.js
  static_files: static/ngsw-worker.js
  upload: static/ngsw-worker\.js

- url: /ngsw\.json
  static_files: static/ngsw.json
  upload: static/ngsw\.json

- url: /static/(.*\.(js|css|json))$
  static_files: static/\1
  upload: static/.*\.(js|css|json)$

- url: /static/assets/(.*\.(gif|png|jpg))$
  static_files: static/assets/\1
  upload: static/assets/.*\.(gif|png|jpg)$

- url: /static/assets/icons/(.*\.(gif|png|jpg|json))$
  static_files: static/assets/icons/\1
  upload: static/assets/icons/.*\.(gif|png|jpg|json)$

- url: /assets/(.*\.(gif|png|jpg))$
  static_files: static/assets/\1
  upload: static/assets/.*\.(gif|png|jpg)$

- url: /assets/icons/(.*\.(gif|png|jpg|json))$
  static_files: static/assets/icons/\1
  upload: static/assets/icons/.*\.(gif|png|jpg|json)$

# If the path is empty, show static index.html file
- url: (.*)/
  static_files: static/index.html
  upload: static/index.html

- url: (.*)
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_files: static/index.html
  upload: static/index.html





