runtime: go
api_version: go1

handlers:
# If the path is empty, show static index.html file
- url: /
  static_files: static/index.html
  upload: static/index.html

# Serve favicon.ico on expected path
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# Otherwise, find file in static directory
- url: /static
  static_dir: static

# All else is handled by Go App
- url: /.*
  script: _go_app