runtime: go111

handlers:
# API calls are handled by Go App
- url: /api
  script: auto

# serve static requests from static dir
- url: /static
  static_dir: static

# Serve favicon.ico on expected path
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

# Serve service workers files on expected paths
- url: /ngsw-worker\.js
  static_files: static/ngsw-worker.js
  upload: static/ngsw-worker\.js

- url: /ngsw\.json
  static_files: static/ngsw.json
  upload: static/ngsw\.json

# serve robots.txt on expected path
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

# If the path is empty, show static index.html file
- url: /
  static_files: static/index.html
  upload: static/index.html
