runtime: go
api_version: go1
handlers:
# If the path is empty, show static index.html file
- url: /
  static_files: static/index.html
  upload: static/index.html

# Otherwise, find file in static directory
- url: /static
  static_dir: static

- url: /.*
  script: _go_app
env_variables:
  CLIENT_ID: '[CLIENT_ID]'